const AUTH = {
  REQUEST: 'AUTH/REQUEST',
  REQUEST_SUCCESS: 'AUTH/REQUEST_SUCCESS',
  REQUEST_ERROR: 'AUTH/REQUEST_ERROR',
  USER_LOGGED_REQUEST: 'AUTH/USER_LOGGED_REQUEST',
  USER_LOGGED_SUCESS: 'AUTH/USER_LOGGED_SUCCESS',
  USER_LOGGED_ERROR: 'AUTH/USER_LOGGED_ERROR',
  SIGNUP_REQUEST: 'AUTH/SIGNUP_REQUEST',
  SIGNUP_REQUEST_SUCCESS: 'AUTH/SIGNUP_REQUEST_SUCCESS',
  SIGNUP_REQUEST_ERROR: 'AUTH/SIGNUP_REQUEST_ERROR',
  LOGOUT_REQUEST: 'AUTH/LOGOUT_REQUEST',
  LOGOUT_REQUEST_SUCCESS: 'AUTH/LOGOUT_REQUEST_SUCCESS',
  LOGOUT_REQUEST_ERROR: 'AUTH/LOGOUT_REQUEST_ERROR',
};

export default AUTH;
