const FORGOT_PASSWORD = {
  RESET: 'FORGOT_PASSWORD/RESET',
  REQUEST: 'FORGOT_PASSWORD/REQUEST',
  REQUEST_SUCCESS: 'FORGOT_PASSWORD/REQUEST_SUCCESS',
  REQUEST_ERROR: 'FORGOT_PASSWORD/REQUEST_ERROR',
};

export default FORGOT_PASSWORD;
