const LOGIN = {
  REQUEST: 'LOGIN/REQUEST',
  REQUEST_SUCCESS: 'LOGIN/REQUEST_SUCCESS',
  REQUEST_ERROR: 'LOGIN/REQUEST_ERROR',
  USER_LOGGED_REQUEST: 'LOGIN/USER_LOGGED_REQUEST',
  USER_LOGGED_SUCESS: 'LOGIN/USER_LOGGED_SUCCESS',
  USER_LOGGED_ERROR: 'LOGIN/USER_LOGGED_ERROR',
};

export default LOGIN;
