const TASK = {
  TASK_UPDATE_REQUEST: 'TASK/TASK_UPDATE_REQUEST',
  TASK_UPDATE_REQUEST_SUCCESS: 'TASK/TASK_UPDATE_REQUEST_SUCCESS',
  TASK_UPDATE_REQUEST_ERROR: 'TASK/TASK_UPDATE_REQUEST_ERROR',
  TASK_CREATE_REQUEST: 'TASK/TASK_CREATE_REQUEST',
  TASK_CREATE_REQUEST_SUCCESS: 'TASK/TASK_CREATE_REQUEST_SUCCESS',
  TASK_CREATE_REQUEST_ERROR: 'TASK/TASK_CREATE_REQUEST_ERROR',
  TASKS_REQUEST: 'TASK/TASKS_REQUEST',
  TASKS_REQUEST_SUCCESS: 'TASK/TASKS_REQUEST_SUCCESS',
  TASKS_REQUEST_ERROR: 'TASK/TASKS_REQUEST_ERROR',
};

export default TASK;
